# Generated by Django 4.2.5 on 2023-11-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='crime_time',
            field=models.DateTimeField(),
        ),
    ]
